<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="portfolio">
	<h3><?php _e('List of projects'); ?></h3>
	<?php if (!empty($projects)) { ?>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('Information'); ?></th>
			<th><?php _e('Image'); ?></th>
		</tr>
		<?php foreach($projects as $project) { ?>
		<tr>
			<td>
				<p><strong><?php _e('ID'); ?> : </strong><?php echo $this->escape($project['id']); ?></p>
				<p><strong><?php _e('Title'); ?> : </strong><?php echo $this->escape($project['title']); ?></p>
				<p><strong><?php _e('Website'); ?> : </strong><?php echo $this->escape($project['website']); ?></p>
				<p><strong><?php _e('Service'); ?> : </strong><?php echo $this->escape($project['service']); ?></p>
				<p><strong><?php _e('Technology'); ?> : </strong><?php echo $this->escape($project['technology']); ?></p>
				<p>
					<a class="btn btn-primary" title="<?php _e('View'); ?>" href="<?php echo $project['url']; ?>"><i class="fa fa-eye"></i> <?php _e('View'); ?></a>
					<a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $project['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
					<a class="btn btn-danger" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $project['id'])); ?>"><i class="fa fa-trash-o"></i> <?php _e('Delete'); ?></a>
				</p>
			</td>
			<td width="200">
				<img width="200" src="<?php echo $project['thumburl']; ?>" alt="<?php echo $this->escape($project['title']); ?>" />
			</td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
	<?php } ?>
</div>