<?php
$this->css(
    [
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ]
);
$this->jQuery();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div id="project-list" class="clearfix">
    <h3><?php _e('List of projects'); ?></h3>
    <?php if (!empty($projects)) { ?>
        <div class="row clearfix">
            <?php foreach ($projects as $project) { ?>
                <?php if ($project['status'] == 5) {
                    $class = 'text-white bg-danger';
                } elseif ($project['status'] == 1) {
                    $class = '';
                } else {
                    $class = 'text-white bg-warning';
                } ?>
                <div class="col-lg-3 col-md-3">
                    <div class="card <?php echo $class; ?>">
                        <img src="<?php echo $project['thumbUrl']; ?>" class="card-img-top w-100" alt="<?php echo $this->escape($project['title']); ?>">
                        <div class="card-body">
                            <h2 class="card-title"><?php echo $this->escape($project['title']); ?></h2>
                            <ul class="card-text">
                                <li class="project-recommended">
                                    <strong><?php _e('Recommended'); ?></strong> :
                                    <?php if ($project['recommended'] == 1) { ?>
                                        <button id="button-<?php echo $project['id']; ?>" type="button" class="btn btn-link"
                                                data-toggle="button"
                                                data-link="<?php echo $this->url('', ['action' => 'recommend', 'id' => $project['id'], 'recommended' => '0']); ?>">
                                            <i class="fas fa-heart"></i></button>
                                    <?php } else { ?>
                                        <button id="button-<?php echo $project['id']; ?>" type="button" class="btn btn-link"
                                                data-toggle="button"
                                                data-link="<?php echo $this->url('', ['action' => 'recommend', 'id' => $project['id'], 'recommended' => '1']); ?>">
                                            <i class="far fa-heart"></i></button>
                                    <?php } ?>
                                </li>
                                <li>
                                    <strong><?php _e('Hits'); ?></strong> : <?php echo $this->escape($project['hits']); ?>
                                </li>
                            </ul>
                            <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                               href="<?php echo $this->url('', ['action' => 'update', 'id' => $project['id']]); ?>"><i class="fa fa-edit"></i> <?php _e(
                                    'Edit'
                                ); ?></a>
                            <?php if ($project['status'] == 1) { ?>
                                <a class="btn btn-success btn-sm" title="<?php _e('View'); ?>" href="<?php echo $project['projectUrl']; ?>" target="_blank"><i
                                            class="fa fa-eye"></i> <?php _e('View'); ?></a>
                            <?php } ?>
                            <?php if ($project['status'] != 5) { ?>
                                <a class="btn btn-danger btn-sm" title="<?php _e('Delete'); ?>"
                                   href="<?php echo $this->url('', ['action' => 'delete', 'id' => $project['id']]); ?>"
                                   onclick="return confirm('<?php echo __('Are you sure to delete this project?'); ?>')">
                                    <i class="fa fa-trash"></i> <?php _e('Delete'); ?>
                                </a>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('No project create yet, Please add project type and after that project'); ?>
        </div>
    <?php } ?>
</div>
<script type="text/javascript">
    (function ($) {
        $("#project-list .project-recommended").on("click", "button", function () {
            systemMessage.wait("<?php _e('Recommended in process'); ?>");
            $.getJSON($(this).attr("data-link")).done(function (result) {
                if (result.ajaxstatus == 1) {
                    if (result.recommended == 1) {
                        var buttonClass = 'fas fa-heart';
                    }
                    if (result.recommended == 0) {
                        var buttonClass = 'far fa-heart';
                    }
                    $('#button-' + result.id + ' i').attr('class', buttonClass);
                    systemMessage.succ(result.message);
                } else {
                    systemMessage.fail(result.message);
                }
            });
        });
    })(jQuery)
</script>