<?php switch ($block['column']) {
    case 1:
        $projectBoxSize = 'col-md-12 col-12';
        $image = 'large';
        break;

    case 2:
        $projectBoxSize = 'col-md-6 col-12';
        $image = 'medium';
        break;

    case 3:
        $projectBoxSize = 'col-md-4 col-12';
        $image = 'medium';
        break;

    case 4:
        $projectBoxSize = 'col-md-3 col-12';
        $image = 'thumb';
        break;

    case 6:
        $projectBoxSize = 'col-md-2 col-12';
        $image = 'thumb';
        break;
} ?>
<div class="portfolio-block clearfix">
    <?php if ($block['list-type'] == 'horizontal') { ?>
        <?php if ($block['blockEffect']) {
            $this->css($this->assetModule('css/block.css', 'portfolio'));
        } ?>
        <div class="clearfix row">
            <?php foreach($block['resources'] as $project) { ?>
                <?php switch ($image) {
                    case 'large':
                        $imageUrl = $project['largeUrl'];
                        break;

                    case 'medium':
                        $imageUrl = $project['mediumUrl'];
                        break;

                    case 'thumb':
                        $imageUrl = $project['thumbUrl'];
                        break;
                } ?>
                <div class="<?php echo $projectBoxSize; ?> portfolio-list-single mb-3" itemscope itemtype="http://schema.org/CreativeWork">
                    <div class="card border-light text-white h-entry">
                        <a <?php if ($project['ribbon']) { ?>class="portfolio-ribbon"<?php } ?> itemprop="url" title="<?php echo $this->escape($project['title']); ?>" href="<?php echo $this->escape($project['projectUrl']); ?>" >
                            <img itemprop="image" class="card-img img-fluid u-photo" src="<?php echo $imageUrl; ?>" alt="<?php echo $this->escape($project['title']); ?>">
                            <?php if ($project['ribbon']) { ?>
                                <p><span><?php echo $this->escape($project['ribbon']); ?></span></p>
                            <?php } ?>
                        </a>
                        <?php if ($block['show_title']) { ?>
                        <div class="card-img-overlay h-100 d-flex flex-column justify-content-end">
                            <h2 itemprop="name" class="card-title">
                                <a class="text-white" title="<?php echo $this->escape($project['title']); ?>" href="<?php echo $this->escape($project['projectUrl']); ?>" >
                                    <?php echo $this->escape($project['title']); ?>
                                </a>
                            </h2>
                        </div>
                        <?php } ?>
                    </div>
                </div>
            <?php } ?>
        </div>
    <?php } elseif ($block['list-type'] == 'slide') { ?>
        <?php if ($block['blockEffect']) {
            $this->jQuery(array(
                'extension/owl.carousel.min.js',
                'extension/owl.carousel.css',
            ));
            $this->css($this->assetModule('css/block.css', 'portfolio'));
            $script = <<<'EOT'
$(document).ready(function($) {
    $('.portfolio-block .owl-carousel').owlCarousel({
        //loop:true,
        //lazyLoad:true,
        margin: 10,
        nav:true,
        rtl:true,
        autoplay:true,
        dots:false,
        autoplayTimeout:12000,
        autoplayHoverPause:true,
        navText: ['<i class="owl-prev fa fa-angle-left"></i>', '<i class="owl-next fa fa-angle-right"></i>'],
        responsive:{
            0:{items:2},
            1000:{items:%s}
        }
    })
});
EOT;
            $script = sprintf($script, $block['column']);
            $this->footScript()->appendScript($script);
        } ?>
        <div class="owl-carousel text-center clearfix">
            <?php foreach ($block['resources'] as $project) { ?>
                <?php switch ($image) {
                    case 'large':
                        $imageUrl = $project['largeUrl'];
                        break;

                    case 'medium':
                        $imageUrl = $project['mediumUrl'];
                        break;

                    case 'thumb':
                        $imageUrl = $project['thumbUrl'];
                        break;
                } ?>
                <div class="portfolio-block-single" itemscope itemtype="http://schema.org/CreativeWork">
                    <div class="thumbnail">
                        <div class="thumbnail-image">
                            <a itemprop="url" title="<?php echo $this->escape($project['title']); ?>" href="<?php echo $project['projectUrl']; ?>" >
                                <img itemprop="image" class="img-fluid" src="<?php echo $imageUrl; ?>" alt="<?php echo $this->escape($project['title']); ?>">
                            </a>
                        </div>
                        <?php if ($block['show_title']) { ?>
                            <div class="caption">
                                <a title="<?php echo $this->escape($project['title']); ?>" href="<?php echo $project['projectUrl']; ?>" >
                                    <h2 itemprop="name" class="small"><?php echo $this->escape($project['title']); ?></h2>
                                </a>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            <?php } ?>
        </div>
    <?php } elseif ($block['list-type'] == 'gallery') { ?>

    <?php } ?>
</div>
