<?php 
	$this->css($this->assetModule('css/block.css', 'portfolio')); 
	$this->jQuery();
	$this->js(array(
	    $this->assetModule('js/modernizr.js', 'portfolio'),
	    $this->assetModule('js/toucheffects.js', 'portfolio'),
	));
?>
<div class="portfolio-block row clearfix"> 
	<ul class="portfolio-block-items">
		<?php  foreach($block['resources'] as $project) { ?>
		<li>
			<figure>
				<img src="<?php echo $project['mediumurl']; ?>" alt="<?php echo $this->escape($project['title']); ?>">
				<figcaption>
					<h6><?php echo $this->escape($project['title']); ?></h6>
					<a title="<?php echo $this->escape($project['title']); ?>" href="<?php echo $this->url('portfolio-portfolio', array('action' => 'project', 'project' => $project['slug'])); ?>"><?php _e('More'); ?></a>
				</figcaption>
			</figure>
		</li>
		<?php } ?>
	</ul>
</div>