<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
	<h1><?php echo $this->escape($title); ?></h1>
	<div class="clearfix">
		<?php foreach($projects as $project) { ?>
		<div class="col-sm-6 col-md-3" itemscope itemtype="http://schema.org/CreativeWork">
			<div class="thumbnail">
				<a itemprop="url" title="<?php echo $this->escape($project['title']); ?>" href="<?php echo $project['projectUrl']; ?>" >
					<img itemprop="image" class="img-polaroid" src="<?php echo $project['thumbUrl']; ?>" alt="<?php echo $this->escape($project['title']); ?>">
				</a>
				<div class="caption">
					<a title="<?php echo $this->escape($project['title']); ?>" href="<?php echo $project['projectUrl']; ?>" >
						<h2 itemprop="name" class="small"><?php echo $this->escape($project['title']); ?></h2>
					</a>
				</div>
			</div>
		</div>
		<?php } ?>
	</div>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
</div>