<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix portfolio-list">
    <div class="page-header">
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <div class="clearfix row">
        <?php foreach($projects as $project) { ?>
            <div class="col-md-3 portfolio-list-single" itemscope itemtype="http://schema.org/CreativeWork">
                <div class="thumbnail">
                    <a <?php if ($project['ribbon']) { ?>class="portfolio-ribbon"<?php } ?> itemprop="url" title="<?php echo $this->escape($project['title']); ?>" href="<?php echo $project['projectUrl']; ?>" >
                        <img itemprop="image" class="img-responsive" src="<?php echo $project['thumbUrl']; ?>" alt="<?php echo $this->escape($project['title']); ?>">
                        <?php if ($project['ribbon']) { ?>
                            <p><span><?php echo $this->escape($project['ribbon']); ?></span></p>
                        <?php } ?>
                    </a>
                    <div class="caption">
                        <a title="<?php echo $this->escape($project['title']); ?>" href="<?php echo $project['projectUrl']; ?>" >
                            <h2 itemprop="name" class="small"><?php echo $this->escape($project['title']); ?></h2>
                        </a>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
    <div class="paginator">
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
    </div>
</div>