<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="portfolio"> 
	<div class="panel panel-default">
  		<div class="panel-heading">
  			<h3 class="panel-title"><?php echo $this->escape($project['title']); ?></h3>
  		</div>
		<div class="panel-body">
			<div class="col-sm-12 col-md-6">
				<img class="img-thumbnail" src="<?php echo $this->escape($project['largeUrl']); ?>" alt="<?php echo $this->escape($project['title']); ?>" />
			</div>
			<div class="col-sm-12 col-md-6">
				<?php if($config['show_information'] && $project['information']) { ?>
				<div class="project-text"><?php echo $project['information']; ?></div>
				<?php } ?>
				<ul class="list-unstyled well">
					<?php if($config['show_service'] && $project['service']) { ?>
					<li><strong><?php _e('Service'); ?> : </strong><?php echo $this->escape($project['service']); ?></li>
					<?php } ?>
					<?php if($config['show_technology'] && $project['technology']) { ?>
					<li><strong><?php _e('Technology'); ?> : </strong><?php echo $this->escape($project['technology']); ?></li>
					<?php } ?>
					<?php if($config['show_website'] && $project['website'] && $project['website_view']) { ?>
					<li><strong><?php _e('Website'); ?> : </strong><?php echo $this->escape($project['website']); ?></li>
					<?php } ?>
					<?php if($config['show_hits']) { ?>
					<li><strong><?php _e('Hits'); ?> : </strong><?php echo $this->escape($project['hits']); ?></li>
					<?php } ?>
				</ul>
				<?php if (isset($tag) && !empty($tag)) { ?>
				<div class="clearfix tagList">
				<?php foreach($tag as $term) { ?>
					<span class="tagItem">
						<a title="<?php echo $this->escape($term); ?>" href="<?php echo $this->url('', array('controller' => 'tag', 'action' => 'index', 'slug' => urlencode($term))); ?>"><i class="fa fa-tag"></i> <?php echo $this->escape($term); ?></a>
					</span>
				<?php } ?>
				</div>
				<?php } ?>
			</div>
		</div>
		<div class="panel-footer">
			<div class="social-list text-left">
				<ul class="list-inline">
					<?php if($config['social_facebook']) { ?>
					<li class="social-facebook"><?php echo $this->facebook(); ?></li>
					<?php } ?>
					<?php if($config['social_twitter']) { ?>
					<li class="social-twitter"><?php echo $this->twitter(); ?></li>
					<?php } ?>
					<?php if($config['social_gplus']) { ?>
					<li class="social-gplus"><?php echo $this->plusone(); ?></li>
					<?php } ?>
				</ul>
	    	</div>
		</div>
	</div>	
</div>