<?php
$this->css($this->assetModule('css/front.css'));
// Set box site
switch ($config['view_column']) {
    case 1:
        $projectBoxSize = 'col-md-12 col-12';
        $image = 'large';
        break;

    case 2:
        $projectBoxSize = 'col-md-6 col-12';
        $image = 'medium';
        break;

    case 3:
        $projectBoxSize = 'col-md-4 col-12';
        $image = 'medium';
        break;

    case 4:
        $projectBoxSize = 'col-md-3 col-12';
        $image = 'thumb';
        break;

    case 6:
        $projectBoxSize = 'col-md-2 col-12';
        $image = 'thumb';
        break;
}

// Set description
if (isset($type) && !empty($type['text_description'])) {
    $description = _strip($type['text_description']);
} elseif (!empty($config['text_description_index'])) {
    $description = _strip($config['text_description_index']);
} else {
    $description = _strip($title);
}
// Set Open Graph tags for meta
$this->doctype('HTML5');
$this->headMeta($this->escape($title), 'og:title', 'property');
$this->headMeta($this->escape($description), 'og:description', 'property');

// Set twitter for meta
$this->headMeta($this->escape($title), 'twitter:title');
$this->headMeta($this->escape($description), 'twitter:description');
?>
<div class="clearfix portfolio-list">
    <?php if (isset($type) && !empty($type['text_description'])) { ?>
        <div class="portfolio-description">
            <h1><?php echo $this->escape($title); ?></h1>
            <div class="clearfix">
                <?php echo $type['text_description']; ?>
            </div>
        </div>
    <?php } elseif (!empty($config['text_description_index'])) { ?>
        <div class="portfolio-description">
            <h1><?php echo $this->escape($title); ?></h1>
            <div class="clearfix">
                <?php echo $config['text_description_index']; ?>
            </div>
        </div>
    <?php } else { ?>
        <div class="page-header">
            <h1><?php echo $this->escape($title); ?></h1>
        </div>
    <?php } ?>
    <?php if ($config['show_type'] && isset($typeList) && !empty($typeList)) { ?>
        <div class="portfolio-type clearfix">
            <ul>
                <?php foreach ($typeList as $typeSingle) { ?>
                    <li<?php if ($typeSingle['active']) { echo ' class="active"';} ?>>
                        <a href="<?php echo $this->escape($typeSingle['typeUrl']); ?>" title="<?php echo $this->escape($typeSingle['title']); ?>">
                            <?php echo $this->escape($typeSingle['title']); ?>
                        </a>
                    </li>
                <?php } ?>
            </ul>
        </div>
    <?php } ?>
    <div class="clearfix row">
        <?php foreach($projects as $project) { ?>
            <div class="<?php echo $projectBoxSize; ?> portfolio-list-single" itemscope itemtype="http://schema.org/CreativeWork">
                <div class="thumbnail">
                    <?php switch ($image) {
                        case 'large':
                            $imageUrl = $project['largeUrl'];
                            break;

                        case 'medium':
                            $imageUrl = $project['mediumUrl'];
                            break;

                        case 'thumb':
                            $imageUrl = $project['thumbUrl'];
                            break;
                    } ?>
                    <div class="thumbnail-image">
                        <a <?php if ($project['ribbon']) { ?>class="portfolio-ribbon"<?php } ?> itemprop="url" title="<?php echo $this->escape($project['title']); ?>" href="<?php echo $this->escape($project['projectUrl']); ?>" >
                            <img itemprop="image" class="img-fluid" src="<?php echo $imageUrl; ?>" alt="<?php echo $this->escape($project['title']); ?>">
                            <?php if ($project['ribbon']) { ?>
                                <p><span><?php echo $this->escape($project['ribbon']); ?></span></p>
                            <?php } ?>
                        </a>
                    </div>
                    <div class="caption">
                        <a title="<?php echo $this->escape($project['title']); ?>" href="<?php echo $this->escape($project['projectUrl']); ?>" >
                            <h2 itemprop="name" class="small"><?php echo $this->escape($project['title']); ?></h2>
                        </a>
                        <?php if ($config['show_phone'] && $project['phone_view'] && !empty($project['phone'])) { ?>
                            <div class="portfolio-phone">
                                <i class="fa fa-phone" aria-hidden="true"></i> <?php echo $this->escape($project['phone']); ?>
                            </div>
                        <?php } ?>
                        <?php /* if ($config['show_website'] && $project['website_view'] && !empty($project['website'])) { ?>
                            <div class="portfolio-website">
                                <a target="_blank" title="<?php echo $this->escape($project['title']); ?>" href="<?php echo $this->escape($project['website']); ?>" >
                                    <?php _e('View website'); ?>
                                </a>
                            </div>
                        <?php } */ ?>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
    <div class="paginator">
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
    </div>
</div>