<?php
$this->css($this->assetModule('css/front.css'));
// Set box site
switch ($config['view_column']) {
    case 1:
        $ProjectBoxSize = 'col-xs-12';
        $image = 'large';
        break;

    case 2:
        $ProjectBoxSize = 'col-xs-6';
        $image = 'medium';
        break;

    case 3:
        $ProjectBoxSize = 'col-xs-4';
        $image = 'thumb';
        break;

    case 4:
        $ProjectBoxSize = 'col-xs-3';
        $image = 'thumb';
        break;

    case 6:
        $ProjectBoxSize = 'col-xs-2';
        $image = 'thumb';
        break;
}
?>
<div class="clearfix portfolio-list">
    <div class="page-header">
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <div class="clearfix row">
        <?php foreach($projects as $project) { ?>
            <div class="<?php echo $ProjectBoxSize; ?> portfolio-list-single" itemscope itemtype="http://schema.org/CreativeWork">
                <div class="thumbnail">
                    <?php switch ($image) {
                        case 'large':
                            $imageUrl = $project['largeUrl'];
                            break;

                        case 'medium':
                            $imageUrl = $project['mediumUrl'];
                            break;

                        case 'thumb':
                            $imageUrl = $project['thumbUrl'];
                            break;
                    } ?>
                    <a <?php if ($project['ribbon']) { ?>class="portfolio-ribbon"<?php } ?> itemprop="url" title="<?php echo $this->escape($project['title']); ?>" href="<?php echo $this->escape($project['projectUrl']); ?>" >
                        <img itemprop="image" class="img-responsive" src="<?php echo $imageUrl; ?>" alt="<?php echo $this->escape($project['title']); ?>">
                        <?php if ($project['ribbon']) { ?>
                            <p><span><?php echo $this->escape($project['ribbon']); ?></span></p>
                        <?php } ?>
                    </a>
                    <div class="caption">
                        <a title="<?php echo $this->escape($project['title']); ?>" href="<?php echo $this->escape($project['projectUrl']); ?>" >
                            <h2 itemprop="name" class="small"><?php echo $this->escape($project['title']); ?></h2>
                        </a>
                        <?php if ($config['show_technology'] && !empty($project['technology'])) { ?>
                            <div class="portfolio-technology">
                                <?php echo $this->escape($project['technology']); ?>
                            </div>
                        <?php } ?>
                        <?php if ($config['show_website'] && !empty($project['website'])) { ?>
                            <div class="portfolio-website">
                                <a target="_blank" title="<?php echo $this->escape($project['title']); ?>" href="<?php echo $this->escape($project['website']); ?>" >
                                    <?php _e('View website'); ?>
                                </a>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
    <div class="paginator">
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
    </div>
</div>