CREATE TABLE `{project}`
(
    `id`                INT(10) UNSIGNED    NOT NULL AUTO_INCREMENT,
    `title`             VARCHAR(255)        NOT NULL DEFAULT '',
    `slug`              VARCHAR(255)        NOT NULL DEFAULT '',
    `type`              INT(10) UNSIGNED    NOT NULL DEFAULT '0',
    `recommended`       TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
    `service`           VARCHAR(255)        NOT NULL DEFAULT '',
    `technology`        VARCHAR(255)        NOT NULL DEFAULT '',
    `website`           VARCHAR(64)         NOT NULL DEFAULT '',
    `website_view`      TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
    `phone`             VARCHAR(16)         NOT NULL DEFAULT '',
    `phone_view`        TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
    `text_description`  TEXT,
    `seo_title`         VARCHAR(255)        NOT NULL DEFAULT '',
    `seo_keywords`      VARCHAR(255)        NOT NULL DEFAULT '',
    `seo_description`   VARCHAR(255)        NOT NULL DEFAULT '',
    `time_create`       INT(10) UNSIGNED    NOT NULL DEFAULT '0',
    `time_update`       INT(10) UNSIGNED    NOT NULL DEFAULT '0',
    `uid`               INT(10) UNSIGNED    NOT NULL DEFAULT '0',
    `hits`              INT(10) UNSIGNED    NOT NULL DEFAULT '0',
    `image`             VARCHAR(255)        NOT NULL DEFAULT '',
    `path`              VARCHAR(16)         NOT NULL DEFAULT '',
    `main_image`        INT(10) UNSIGNED    NOT NULL DEFAULT '0',
    `additional_images` TEXT,
    `status`            TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
    `point`             INT(10)             NOT NULL DEFAULT '0',
    `count`             INT(10) UNSIGNED    NOT NULL DEFAULT '0',
    `favourite`         INT(10) UNSIGNED    NOT NULL DEFAULT '0',
    `commentby`         VARCHAR(255)        NOT NULL DEFAULT '',
    `comment`           TEXT,
    `customer`          VARCHAR(255)        NOT NULL DEFAULT '',
    `version`           VARCHAR(64)         NOT NULL DEFAULT '',
    `size`              VARCHAR(64)         NOT NULL DEFAULT '',
    `link_1`            VARCHAR(64)         NOT NULL DEFAULT '',
    `link_2`            VARCHAR(64)         NOT NULL DEFAULT '',
    `link_3`            VARCHAR(64)         NOT NULL DEFAULT '',
    `link_4`            VARCHAR(64)         NOT NULL DEFAULT '',
    `link_5`            VARCHAR(64)         NOT NULL DEFAULT '',
    `image_1`           VARCHAR(255)        NOT NULL DEFAULT '',
    `image_2`           VARCHAR(255)        NOT NULL DEFAULT '',
    `image_3`           VARCHAR(255)        NOT NULL DEFAULT '',
    `image_4`           VARCHAR(255)        NOT NULL DEFAULT '',
    `image_5`           VARCHAR(255)        NOT NULL DEFAULT '',
    PRIMARY KEY (`id`),
    UNIQUE KEY `slug` (`slug`),
    KEY `title` (`title`),
    KEY `time_create` (`time_create`),
    KEY `status` (`status`),
    KEY `type` (`type`),
    KEY `recommended` (`recommended`),
    KEY `project_order` (`time_create`, `id`),
    KEY `project_order_recommended` (`recommended`, `time_create`, `id`)
);

CREATE TABLE `{type}`
(
    `id`               INT(10) UNSIGNED    NOT NULL AUTO_INCREMENT,
    `title`            VARCHAR(255)        NOT NULL DEFAULT '',
    `slug`             VARCHAR(255)        NOT NULL DEFAULT '',
    `status`           TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    `view_order`       TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    `main_image`       INT(10) UNSIGNED    NOT NULL DEFAULT '0',
    `text_description` TEXT,
    PRIMARY KEY (`id`),
    UNIQUE KEY `slug` (`slug`),
    KEY `status` (`status`)
);